#!/usr/bin/env bash
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STANDARDS_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
GUARD="$STANDARDS_DIR/runtime/claude-code/hooks/usage-guard.sh"
RESULTS="$SCRIPT_DIR/results.md"
TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/enforcement-in-action.XXXXXX")"
trap 'rm -rf "$TMP_DIR"' EXIT

blocked_payload="$TMP_DIR/blocked-agent.json"
allowed_payload="$TMP_DIR/allowed-agent.json"
blocked_output="$TMP_DIR/blocked-output.json"
allowed_output="$TMP_DIR/allowed-output.json"

cat > "$blocked_payload" <<'JSON'
{
  "hook_event_name": "PreToolUse",
  "tool_name": "Agent",
  "tool_input": {
    "subagent_type": "conductor",
    "model": "conductor-model",
    "estimated_usage_pct": 95,
    "description": "Violation: over-budget conductor-model subagent spawn",
    "prompt": "Spawn an expensive conductor to fan out the review."
  }
}
JSON

cat > "$allowed_payload" <<'JSON'
{
  "hook_event_name": "PreToolUse",
  "tool_name": "Agent",
  "tool_input": {
    "subagent_type": "researcher",
    "model": "haiku",
    "estimated_usage_pct": 12,
    "description": "Compliant cheap-model subagent spawn",
    "prompt": "Collect narrow references for one check."
  }
}
JSON

"$GUARD" block < "$blocked_payload" > "$blocked_output" 2>&1
blocked_rc=$?

"$GUARD" block < "$allowed_payload" > "$allowed_output" 2>&1
allowed_rc=$?

blocked_decision="$(grep -o '"decision":"[^"]*"' "$blocked_output" | head -n 1 || true)"
allowed_decision="$(grep -o '"decision":"[^"]*"' "$allowed_output" | head -n 1 || true)"

{
  printf '# The enforcement is not a diagram; here is it firing\n\n'
  printf 'Generated by `proof/enforcement-in-action/demo.sh`.\n\n'
  printf '## BEFORE: attempted violating call\n\n'
  printf 'Command: `runtime/claude-code/hooks/usage-guard.sh block`\n\n'
  printf 'Input payload:\n\n'
  printf '```json\n'
  sed 's/[[:space:]]*$//' "$blocked_payload"
  printf '\n```\n\n'
  printf '## AFTER: violation blocked\n\n'
  printf 'Exit code: `%s`\n\n' "$blocked_rc"
  printf 'Guard output:\n\n'
  printf '```json\n'
  sed 's/[[:space:]]*$//' "$blocked_output"
  printf '\n```\n\n'
  printf 'Result: `%s`, expected `"decision":"block"` with exit `2`.\n\n' "$blocked_decision"
  printf '## Contrast: compliant cheap-model spawn allowed\n\n'
  printf 'Command: `runtime/claude-code/hooks/usage-guard.sh block`\n\n'
  printf 'Input payload:\n\n'
  printf '```json\n'
  sed 's/[[:space:]]*$//' "$allowed_payload"
  printf '\n```\n\n'
  printf 'Exit code: `%s`\n\n' "$allowed_rc"
  printf 'Guard output:\n\n'
  printf '```json\n'
  sed 's/[[:space:]]*$//' "$allowed_output"
  printf '\n```\n\n'
  printf 'Result: `%s`, expected `"decision":"allow"` with exit `0`.\n' "$allowed_decision"
} > "$RESULTS"

if [ "$blocked_rc" -ne 2 ] || [ "$blocked_decision" != '"decision":"block"' ]; then
  printf 'FAIL enforcement-in-action: violation was not hard-blocked\n' >&2
  exit 1
fi

if [ "$allowed_rc" -ne 0 ] || [ "$allowed_decision" != '"decision":"allow"' ]; then
  printf 'FAIL enforcement-in-action: compliant cheap-model spawn was not allowed\n' >&2
  exit 1
fi

printf 'PASS enforcement-in-action: violation blocked and compliant contrast allowed\n'
