#!/usr/bin/env bash
# measure.sh - loop-spec adoption count (derived, no metered API).
#
# Counts loop specifications in the local loops directory, when one exists.
# Public clones of this repo ship no loops directory, so they should report
# count=0 cleanly instead of failing.
#
#   bash measure.sh            # print the local count
#   bash measure.sh --emit     # write a local measurement to results.md
#   bash measure.sh --print    # print the local count

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STANDARDS_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
REPO_ROOT="$(cd "$STANDARDS_DIR/.." && pwd)"
RESULTS="$SCRIPT_DIR/results.md"

# Resolve the canonical loops directory. The Mini canonical keeps loop specs at
# compound-ai/loops/ (the live tree) or loops/ (the sandbox copy). Probe both.
LOOPS_DIR=""
for cand in "$REPO_ROOT/compound-ai/loops" "$REPO_ROOT/loops" "$STANDARDS_DIR/loops"; do
  if [ -d "$cand" ]; then LOOPS_DIR="$cand"; break; fi
done

# A loop spec is a *.spec.md file in the loops directory.
spec_files() { find "$LOOPS_DIR" -maxdepth 1 -type f -name '*.spec.md' -print | sort; }

if [ -z "$LOOPS_DIR" ]; then
  COUNT=0
  LOOPS_REL="none found"
  NO_LOOPS=1
else
  COUNT=$(spec_files | grep -c .)
  LOOPS_REL="${LOOPS_DIR#$REPO_ROOT/}"
  NO_LOOPS=0
fi

render() {
  if [ "$NO_LOOPS" -eq 1 ]; then
    cat <<EOF
# Local loop-spec count

This measures the loop specs in your own \`loops/\` directory. This public repo
ships none, so count=0.

| Set | Count |
|---|---:|
| Local loop specifications | 0 |

Method: look for \`*.spec.md\` in \`compound-ai/loops/\`, \`loops/\`, then
\`operating-standards/loops/\`. No directory was found, so the measurement is
complete and zero.
EOF
    return
  fi

  cat <<EOF
# Local loop-spec count

Generated by \`measure.sh\`. No metered API.

## Count

**${COUNT}** local loop specifications in \`${LOOPS_REL}/\`.

## Method

\`find\` for \`*.spec.md\` in the first local loops directory found. Pure shell,
no network, no API key. This is a local measurement, not a public-repo proof.
EOF
}

case "${1:---print}" in
  --print|"")
    render
    ;;
  --emit|--write-results)
    render > "$RESULTS"
    printf 'loop-adoption: %s local loop specs in %s\n' "$COUNT" "$LOOPS_REL"
    printf 'wrote %s\n' "${RESULTS#$STANDARDS_DIR/}"
    ;;
  *)
    printf 'usage: %s [--emit|--write-results|--print]\n' "$0" >&2
    exit 2
    ;;
esac
